### ISSUE TITLE
Naming to support other backends

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-kubernetes#23] opened 2017-07-27 14:32 UTC
The Elasticsearch backend is ready, I assume we'll eventually want to have templates for it as well. How should this affect the naming of directories and files in this repo?

**Comment by pavolloffay** [comment] 2017-07-27 14:54
First we have to split cassandra related stuff from jaeger deployment. Adding ES will probably require some changes to jaeger deployment (use some flag etc.). The problem is that K8s resource files do not support parameters, so we might use something like helm (I don't know yet).

In terms of storage templates maybe it would be if we could reuse ES deployment from k8s and just make sure that it works with Jaeger.

**Comment by pavolloffay** [comment] 2017-10-25 10:51
Related to #54

**Comment by pavolloffay** [comment] 2018-01-29 10:34
I will close this in favour of #54

**Closed by pavolloffay** 2018-01-29 10:34 UTC
