### ISSUE TITLE
Intermittent ES failure with NPE

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-kubernetes#66] opened 2018-01-12 15:50 UTC
As can be scene [here](https://travis-ci.org/jaegertracing/jaeger-kubernetes/jobs/328164324).

```
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 49.396 s <<< FAILURE! - in io.jaegertracing.kubernetes.ElasticearchETest
[ERROR] testReportSpanToCollector(io.jaegertracing.kubernetes.ElasticearchETest)  Time elapsed: 1.212 s  <<< ERROR!
java.lang.RuntimeException: Could not lookup value for field private java.net.URL io.jaegertracing.kubernetes.deployment.BaseETest.collectorUrl
Caused by: java.lang.NullPointerException
[ERROR] testUiResponds(io.jaegertracing.kubernetes.ElasticearchETest)  Time elapsed: 0.317 s  <<< ERROR!
java.lang.RuntimeException: Could not lookup value for field private java.net.URL io.jaegertracing.kubernetes.deployment.BaseETest.collectorUrl
Caused by: java.lang.NullPointerException
[ERROR] hitDependencyScreen(io.jaegertracing.kubernetes.ElasticearchETest)  Time elapsed: 0.326 s  <<< ERROR!
java.lang.RuntimeException: Could not lookup value for field private java.net.URL io.jaegertracing.kubernetes.deployment.BaseETest.collectorUrl
Caused by: java.lang.NullPointerException
[ERROR] testDependencyLinks(io.jaegertracing.kubernetes.ElasticearchETest)  Time elapsed: 0.249 s  <<< ERROR!
java.lang.RuntimeException: Could not lookup value for field private java.net.URL io.jaegertracing.kubernetes.deployment.BaseETest.collectorUrl
Caused by: java.lang.NullPointerException
[ERROR] testReportZipkinSpanToCollector(io.jaegertracing.kubernetes.ElasticearchETest)  Time elapsed: 0.173 s  <<< ERROR!
java.lang.RuntimeException: Could not lookup value for field private java.net.URL io.jaegertracing.kubernetes.deployment.BaseETest.collectorUrl
Caused by: java.lang.NullPointerException
Deleting namespace: itest-f450b2be...
Namespace: itest-f450b2be, successfully deleted
```

**Comment by pavolloffay** [comment] 2018-01-29 10:34
This seems to be duplicate of https://github.com/jaegertracing/jaeger-kubernetes/issues/44. Please reopen if it's not the case.

**Closed by pavolloffay** 2018-01-29 10:34 UTC
